core/correspondencia/urls.py
from django.urls import path
from core.correspondencia.views import *

urlpatterns = [
    path('inicio/', IndexView.as_view(), name="index"),
    path('entrada/', EntradaView.as_view(), name="entrada"),
    path('salida/', SalidaView.as_view(), name="salida"),
    path('archivo/', ArchivoView.as_view(), name="archivo"),
]

proyectoCorrespondencia/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('correspondencia/', include('core.correspondencia.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/correspondencia/models.py
from datetime import date
from django.db import models
from django.utils.timezone import now

# Create your models here.

class Correspondencia(models.Model):
    AZ = [
        ('1. Vice Docencia',( 
            ('1.1. Oficios', '1.1. Oficios'),
            ('1.2. Citaciones-Circulares-Memorandos', '1.2. Citaciones-Circulares-Memorandos'),
            ('1.2. Certificados', '1.2. Certificados'),
        )),
        (
            '2. SecretarGeneral',(
            ('2.1. Oficios', '2.1. Oficios'),
            ('2.2. Comisiones', '2.2. Comisiones'),
            ('2.3. PQRS', '2.3. PQRS'),
        )),
        (
            '3. Consejos',(
            ('3.1. Acuerdo CS', '3.1. Acuerdo CS'),
            ('3.2. Resoluciones CS', '3.2. Resoluciones CS'),
            ('3.3. Acuerdos CA', '3.3. Acuerdos CA'),
            ('3.4. Resoluciones CA', '3.4. Resoluciones CA'),
            ('3.5. Actas CA', '3.5. Actas CA'),
        )),
        (
            '4. Oficinas Asesoras de Jur y Control Disciplinario',(
            ('4.1. Oficios Jur', '4.1. Oficios Jur'),
            ('4.2. Conceptos Jur', '4.2. Conceptos Jur'),
            ('4.3. Oficios CD ', '4.3. Oficios CD '),
        )),
        (
            '5. Oficina Asesora de GestiHumana y Desarrollo de Personal',(
            ('5.1. GestiHumana', '5.1. GestiHumana'),
            ('5.2. Personal', '5.2. Personal'),
            ('5.3. Desarrollo Organizacional', '5.3. Desarrollo Organizacional'),
        )),
        (
            '6. Rectory Vicerector',(
            ('6.1. Rector', '6.1. Rector'),
            ('6.2. Vice-Administrativa', '6.2. Vice-Administrativa'),
            ('6.3. Vice-Bienestar', '6.3. Vice-Bienestar'),
            ('6.4. Vice-Calidad', '6.4. Vice-Calidad'),
            ('6.5. Vice-Extension', '6.5. Vice-Extension'),
            ('6.6. Vice-Internacionalizaci', '6.6. Vice-Internacionalizaci'),
            ('6.7. Vice-Investigaci', '6.7. Vice-Investigaci'),
        )),
        (
            '7. Oficina Asesoras de Planeaci y Control Interno',(
            ('7.1. Oficios P', '7.1. Oficios P'),
            ('7.2. Oficios CI', '7.2. Oficios CI'),
        )),
        (
            '8. AuditorControl Interno',(
            ('8.1. AuditorCI', '8.1. AuditorCI'),
        )),
        (
            '9. Facultades Centro',(
            ('9.1. Fac. C. Humanas', '9.1. Fac. C. Humanas'),
            ('9.2. Fac. C. Sociales', '9.2. Fac. C. Sociales'),
            ('9.3. Fac. Derecho', '9.3. Fac. Derecho'),
        )),
        (
            '10. Facultades Piedra',(
            ('10.1. Fac. C. Econ', '10.1. Fac. C. Econ'),
            ('10.2. Fac. C. Exactas y Naturales', '10.2. Fac. C. Exactas y Naturales'),
            ('10.3. Fac. Ingenier', '10.3. Fac. Ingenier'),
        )),
        (
            '11. Facultades Salud',(
            ('11.1. Fac. C. Farmac', '11.1. Fac. C. Farmac'),
            ('11.2. Fac. Enfermer', '11.2. Fac. Enfermer'),
            ('11.3. Fac. Medicina', '11.3. Fac. Medicina'),
            ('11.4. Fac. Odontolog', '11.4. Fac. Odontolog'),
        )),
        (
            '12. Institutos',(
            ('12.1. Inst. Inmunolog', '12.1. Inst. Inmunolog'),
            ('12.2. Inst. Hidr', '12.2. Inst. Hidr'),
            ('12.3 Inst. Estudios del Caribe', '12.3 Inst. Estudios del Caribe'),
            ('12.4. Inst. MatemAplicada', '12.4. Inst. MatemAplicada'),
            ('12.5. Inst. PolPublicas IPREG', '12.5. Inst. PolPublicas IPREG'),
        )),
        (
            '13. Rutas Acad y Salidas de Campo',(
            ('13.1. Rutas Acad', '13.1. Rutas Acad'),
            ('13.2. Salidas de Campo', '13.2. Salidas de Campo'),
        )),
        ('14. Otras Oficinas Internas', '14. Otras Oficinas Internas'),
        ('15. Correspondencia Externa', '15. Correspondencia Externa'),
        ('16. Solicitud de Docentes', '16. Solicitud de Docentes'),
        ('17. Correos electr', '17. Correos electr'),
        ('18. Informe de gesti', '18. Informe de gesti'),
        (
            '19. Centros',(
            ('19.1. C. de admisiones', '19.1. C. de admisiones'),
            ('19.2. C. de autoevaluaci', '19.2. C. de autoevaluaci'),
            ('19.3  C. de informaciy D.', '19.3  C. de informaciy D.'),
            ('19.4. C. de inform', '19.4. C. de inform'),
            ('19.5. C. de postgrado', '19.5. C. de postgrado'),
            ))

    ]
    radicado = models.CharField(max_length=10, unique=True, blank=False, default="RVD")
    recibido_de = models.CharField(max_length=50, unique=False, blank=False, default="")
    fecha_recibido = models.DateField(default=now)
    asunto = models.CharField(max_length=100, blank=False, null=False)
    numero_folios = models.PositiveIntegerField(null=False, default=1)
    firmado_por = models.CharField(max_length=50, unique=False, blank=False)
    cargo_firmante = models.CharField(max_length=50, unique=False, blank=False)
    enviado_a = models.CharField(max_length=20, unique=False, blank=False, default="none")
    fecha_envio = models.DateField(default=now)
    almacenado_AZ = models.CharField(max_length=100, choices=AZ)
    observaciones = models.TextField(blank=False,)
    entrada = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return ("Correspondencia{radicado=" + self.radicado + ", recibido_de=" + self.recibido_de + ", fecha_recibido=" + self.fecha_recibido.__str__() + ", asunto=" + self.asunto + ", numero_folios=" + str(self.numero_folios) + ", firmado_por=" + self.firmado_por + ", cargo_firmante=" + self.cargo_firmante + ", enviado_a=" + self.enviado_a + ", fecha_envio=" + self.fecha_envio.__str__() + ", almacenado_AZ=" + self.almacenado_AZ + ", observaciones=" + self.observaciones + ", entrada=" + str(self.entrada) + '}')

core/correspondencia/forms.py
from socket import fromshare
from django import forms

class EntradaForm(forms.Form):

    fields = ['radicado', 'recibido_de', 'fecha_recibido', 'asunto', 'numero_folios', 'firmado_por', 'cargo_firmante', 'enviado_a', 'fecha_envio', 'almacenado_AZ', 'observaciones', 'entrada']
    labels = []

core/correspondencia/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from core.correspondencia.models import Correspondencia
from django.views.generic import TemplateView, CreateView, FormView, UpdateView, DeleteView
from django.urls import reverse_lazy
from core.correspondencia.forms import EntradaForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

#@method_decorator(login_required, name='dispatch')
class IndexView(TemplateView):
    template_name = "index.html"


class EntradaView(FormView):
    model = Correspondencia
    form_class = EntradaForm
    template_name = "entrada.html"
    #success_url = "/correspondencia/"

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, 'Entrada registrada'
        )
        return super(EntradaView, self).form_valid(form)

class SalidaView(FormView):
    model = Correspondencia
    template_name = "salida.html"
    form_class = EntradaForm
    #success_url = "/correspondencia/"

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, 'Salida registrada'
        )
        return super(SalidaView, self).form_valid(form)

    
class ArchivoView(FormView):
    model = Correspondencia
    template_name = "archivo.html"
    form_class = EntradaForm

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, 'Salida registrada'
        )
        return super(ArchivoView, self).form_valid(form)

class DeleteView(DeleteView):
    model = Correspondencia
    success_url = reverse_lazy('index')

templates/archivo.html
{% extends 'base.html' %}
{% block title %}Archivo Correspondencia{% endblock %}
{% block active_archivo %} active {% endblock %}
{% block content %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/icons/bootstrap-icons.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
  <!-- select2 -->
  <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome/all.min.css'%}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  
	{% block css %} {% endblock %}
	<title>{%block title %} {% endblock %}</title>
</head>
<body>
<!-- top navigation bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <!-- offcanvas trigger -->
    <button class="navbar-toggler me-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      <i class="navbar-toggler-icon" data-bs-target="#offcanvasExample"></i>
    </button>
    <!-- end offcanvas trigger -->
    <a class="navbar-brand fw-bold text-uppercase me-auto" href="{% url 'index' %}">Correspondencia</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex ms-auto">
        <div class="input-group my-3 my-lg-0">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i> </button>
      </div>
      </form>
    
	    <ul class="navbar-nav mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	          <i class="bi bi-person-fill"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Usuario</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Cerrar sesión</a></li>
          </ul>
        </li>

      </ul>

    </div>
  </div>
</nav>
<!-- top navigation bar -->
<!-- offcanvas -->

<div class="offcanvas offcanvas-start bg-dark text-white sidebar-nav" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">

  <div class="offcanvas-body p-0">
    <nav class="navbar-dark">
      
      <ul class="navbar-nav">
        
        <li>
          <a href="{% url 'entrada' %}" class="nav-link px-2 {% block active_entrada %}{% endblock %}">
            <span class="me-2">
              <i class="bi bi-box-arrow-in-down"></i>
            </span>
            <span>Entrada</span>
          </a>
        </li>

        <li><hr class="dropdown-divider"></li>

        <li>
          <a href="{% url 'salida' %}" class="nav-link px-2 {% block active_salida %}{% endblock %}">
            <span class="me-2">
              <i class="bi bi-box-arrow-up"></i>
            </span>
            <span>Salida</span>
          </a>
        </li>
        <li><hr class="dropdown-divider"></li>

        <li>
          <a href="{% url 'archivo' %}" class="nav-link px-2 {% block active_archivos %}{% endblock %}">
            <span class="me-2">
              <i class="bi bi-archive-fill"></i>
            </span>
            <span>Archivo</span>
          </a>
        </li>
        <li><hr class="dropdown-divider"></li>
      </ul>
    
    </nav>
    
    
  </div>
</div>

<!-- end offcanvas -->

<!-- Sección de contenido -->
<main class="mt-5 pt-3">
{% block content %} {% endblock %}

</main>
<!-- Fin Sección de contenido -->



<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'js/select2/select2.full.min.js' %}"></script>
<script src="{% static 'js/moment/moment.min.js'%}"></script>
<script type="text/javascript">
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Date picker
    $('#reservationdate').datepicker({
        format: 'L'
    });

    //Date and time picker
    $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datepicker({
      format: 'LT'
    })

  })
  
</script>
{% block javascript %} {% endblock %}
</body>
</html>

templates/entrada.html
{% extends 'base.html' %}
{% block title %} Entrada Correspondencia{% endblock %}
{% block active_entrada %} active {% endblock %}
{% block content %}
	<div class="container ">


	<h3>Entrada de correspondencia</h3>


	<form method="post">
			{% csrf_token %}
	<div class="mb-3 row">
		<label for="radicado" class="col-sm-2 col-form-label">Radicado: </label>
		<div class="col-sm-4">
			<input type="text" name="radicado" class="form-control" required id="id_radicado" placeholder="RVD-0000">
		</div>
	</div>
		<div class="mb-3 row">
		<label for="recibido_de" class="col-sm-2 col-form-label">Recibido de: </label>
		<div class="col-sm-4">
			<input type="text" name="recibido_de" class="form-control" required id="id_recibido_de">
		</div>
		</div>
		<div class="mb-3 row">
			
			<label for="fecha_recibido" class="col-sm-2 col-form-label">Fecha recibido: </label>
			<div class="col-sm-4">

				<div class="input-group date" id="reservationdate" data-target-input="nearest">
					<input type="text" id="fecha_recibido" name="fecha_recibido" class="form-control datetimepicker-input" data-target="#reservationdate"/>
					<div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
						<div class="input-group-text"><i class="bi bi-calendar"></i></div>
					</div>
				</div>
			</div>

		</div>

		<div class="mb-3 row">

				<label for="asunto" class="col-sm-2 col-form-label">Asunto: </label>
			<div class="col-sm-4">
				<input type="text" name="asunto" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="num_folios" class="col-sm-2 col-form-label">Número folios: </label>
			<div class="col-sm-4">
				<input type="text" name="num_folios" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="firmado_por" class="col-sm-2 col-form-label">Firmado por: </label>
			<div class="col-sm-4">
				<input type="text" name="firmado_por" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="cargo_firm" class="col-sm-2 col-form-label">Cargo firmante: </label>
			<div class="col-sm-4">
				<input type="text" name="cargo_firm" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="enviado_a" class="col-sm-2 col-form-label">Enviado a: </label>
			<div class="col-sm-4">
				<input type="text" name="enviado_a" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="fecha_envio" class="col-sm-2 col-form-label">Fecha envío: </label>
			<div class="col-sm-4">
				<input type="text" name="fecha_envio" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="almacenado" class="col-sm-2 col-form-label">Almacenado AZ: </label>
			<div class="col-sm-4">
				<input type="text" name="almacenado" class="form-control" required id="id_asunto">
			</div>

		</div>

		<div class="mb-3 row">

				<label for="observaciones" class="col-sm-2 col-form-label">Observaciones: </label>
			<div class="col-sm-4">
				<input type="text" name="observaciones" class="form-control" required id="id_asunto">
			</div>

		</div>
		<div class="mb-5 row">


			<div class="col-sm-1">
				<input type="submit" class="col-sm-1 form-control btn-success" value="Enviar">
			</div>

		</div>

		</form>

	</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

templates/salida.html
{% extends 'base.html' %} 
{% block title %}Salida Correspondencia{% endblock %}
{% block active_salida %} active {% endblock %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
        <p> Buscar</p>
        <div class="input-group input-group-sm">
            <input type="text" class="form-control" placeholder="Radicado">
            <span class="input-group-append">
              <button type="button" class="btn btn-info btn-flat buscar"><i class="bi bi-search"></i></button>
            </span>
    </div>
  </div>
</div>
{% endblock %}

{% block js %} 
<script>

</script>
{% endblock %}